### PR TITLE
Insertion PR for roslyn

### PR DESCRIPTION
**Pull request by maryamariyan**
Needed for https://github.com/dotnet/vscode-csharp/pull/6960#issuecomment-2019103906

cc @ryzngard @davidwengier @dibarbet

### CODE REVIEW

**Comment by davidwengier** [comment]
Did we really only miss it by one build? That seems terribly unlucky 😁

My only real comment is that we should probably just cherry-pick this commit into the other PR, so it all goes at once. No need to do two PRs I don't think?

**Comment by ryzngard** [comment]
> Did we really only miss it by one build? That seems terribly unlucky 😁
> 
> My only real comment is that we should probably just cherry-pick this commit into the other PR, so it all goes at once. No need to do two PRs I don't think?

Yes we did 😢

**Comment by dibarbet** [comment]
> My only real comment is that we should probably just cherry-pick this commit into the other PR, so it all goes at once. No need to do two PRs I don't think?

Agree with this - fine to cherry-pick this change into your previous PR that adds the flag.  Also make sure to run `gulp updateRoslynVersion` locally to update the new package versions in the nuget feed

**Comment by maryamariyan** [comment]
sounds good, I'll close this and cherry pick on the other pr

**Pull request closed without merging**
