### PR TITLE
Bump Razor to 7.0.0-preview.23455.5

### PR DESCRIPTION
**Pull request by davidwengier**
Brings in the fix for https://github.com/dotnet/razor/issues/9224

Also sneakily cleaning up the client side of https://github.com/dotnet/razor/pull/9203

### CODE REVIEW

**Review by allisonchou — APPROVED** [review]
Should we also be updating [CHANGELOG.md](https://github.com/dotnet/vscode-csharp/blob/main/CHANGELOG.md)?

**Comment by davidwengier** [comment]
Good question. I have not been doing that. I thought it became automatic at some point. @dibarbet do I update it?

**Comment by dibarbet** [comment]
> Good question. I have not been doing that. I thought it became automatic at some point. @dibarbet do I update it?

I've been updating the changelog based on what is in your PR descriptions.  However it would be better if you update it here, then I don't have to go searching :)

**Comment by davidwengier** [comment]
Oh god, sorry! You should have told me :P

**Pull request merged**
