### PR TITLE
Update changelog based on last roslyn update

### PR DESCRIPTION
**Pull request by dibarbet**

### CODE REVIEW

**Review by ryzngard — APPROVED** [review]
Thanks for getting this :) I was trying to find the commit of the last insertion to compare

**Comment by dibarbet** [comment]
> Thanks for getting this :) I was trying to find the commit of the last insertion to compare

Not sure if you know this trick, but easiest way to find it is to look up the package version on the msft_consumption feed, which has the commit sha in the description, e.g.
https://dev.azure.com/azure-public/vside/_artifacts/feed/msft_consumption/NuGet/Microsoft.CodeAnalysis.LanguageServer.osx-arm64/overview/4.13.0-1.24501.3

**Comment by ryzngard** [comment]
> > Thanks for getting this :) I was trying to find the commit of the last insertion to compare
> 
> Not sure if you know this trick, but easiest way to find it is to look up the package version on the msft_consumption feed, which has the commit sha in the description, e.g. [dev.azure.com/azure-public/vside/_artifacts/feed/msft_consumption/NuGet/Microsoft.CodeAnalysis.LanguageServer.osx-arm64/overview/4.13.0-1.24501.3](https://dev.azure.com/azure-public/vside/_artifacts/feed/msft_consumption/NuGet/Microsoft.CodeAnalysis.LanguageServer.osx-arm64/overview/4.13.0-1.24501.3)

I did not! I always find the build that produced the artifacts for the sha... 🤦

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
> I did not! I always find the build that produced the artifacts for the sha... 🤦

Same!

**Pull request merged**
