### PR TITLE
Add XAML syntax highlighting and grammar

### PR DESCRIPTION
**Pull request by mgoertz-msft**
Add support for XAML language-configuration and tmLanguage jsons:
- xaml.tmLanguage.json comes from the MAUI Dev Kit
- language-configuration.json comes from VS

### CODE REVIEW

**Comment by mgoertz-msft** [comment]
FYI @dibarbet

**Review by dibarbet — APPROVED** [review]
I didn't review the syntaxes in depth, but the changes seem good.

**Comment by mgoertz-msft** [comment]
Thanks @dibarbet! That's fine, I didn't change those file from where they came from anyway.

**Comment by mgoertz-msft** [comment]
@dibarbet Do you mind re-running the failed checks, which seem unrelated, when you get a moment?

**Comment by dibarbet** [comment]
> @dibarbet Do you mind re-running the failed checks, which seem unrelated, when you get a moment?

@mgoertz-msft I've re-run 3 times, but they seem to be failing for a base infra error.  Planning on taking a look at what is going on in the next day or two.

**Comment by mgoertz-msft** [comment]
Oh, ok. Thanks!

**Comment by dibarbet** [comment]
@mgoertz-msft fix for windows tests is here - https://github.com/dotnet/vscode-csharp/pull/7070
Once it goes in I'll re-run the tests.

**Pull request merged**
