### PR TITLE
Update message keys for configuration.razor.trace

### PR DESCRIPTION
**Pull request by rsandbach**
PR for #6893

### CODE REVIEW

**Comment by rsandbach** [comment]
@dotnet-policy-service agree

**Comment by davidwengier** [comment]
@Cosifne Was I wrong to think these should have automatically been updated by the localization process, as would happen with `.xlf` files in VS land? Is there some other part of the process I missed to clean up localization?

**Comment by Cosifne** [comment]
@davidwengier  the key here is auto-generated by vscode-l10n, not sure why it's out-off sync originally, let me check

**Comment by rsandbach** [comment]
> if possible could you check if the config is still grouped with other razor configs?

I think this is what you are asking. There are other Razor settings in the LSP Server group, but they are not all together as one. 

image

Razor > Server is not grouped with Razor > Language Server

image

When editing the settings JSON it also fails to translate the descriptions of the settings:
image

Out of curiosity, is there a difference between Razor > Server and Razor > Language Server?

**Comment by davidwengier** [comment]
> Out of curiosity, is there a difference between Razor > Server and Razor > Language Server?

Naming is hard :)

**Review by davidwengier — APPROVED** [review]
Thanks for the PR! I took the liberty of pushing a change to clean up the unused strings, for each trace value. Thanks also for noticing the issue with the code action handler!

**Pull request merged**
