### PR TITLE
Debugger docs: point to official docs

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This PR updates the debugger docs to just point at the official documentation rather than duplicating their content.

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
Should we hold off on merging this change until we release a version of the extension with https://github.com/dotnet/vscode-csharp/pull/6659 ?

Seems like the strings in the current released extension point to these files

**Comment by gregg-miskelly** [comment]
> Should we hold off on merging this change until we release a version of the extension with #6659 ?

It's required because the aka.ms links point at the release branch's copy of the docs. Though maybe we should do it anyway just in case.

**Review by WardenGnaw — APPROVED** [review]

**Review by WardenGnaw — APPROVED** [review]

**Comment by gregg-miskelly** [comment]
@davidwengier I am having trouble getting the `test:razorintegration:BasicRazorApp2_1` test to pass on macOS. Are you the right person to take a look? I have re-run the test ~5 times now without success. This PR doesn't contain code changes, so I don't see how it could be related.

From the log, I think this is the first failure:
```
2023-11-30T22:00:25.4986430Z   console.log
2023-11-30T22:00:25.5000690Z     Extension Log Directory: /Users/runner/work/1/s/.vscode-test/user-data/logs/20231130T220005/window1/exthost/ms-dotnettools.csharp
2023-11-30T22:00:25.5015900Z 
2023-11-30T22:00:25.5039880Z       at Object.<anonymous> (../integrationTests/integrationHelpers.ts:42:13)
2023-11-30T22:00:25.5059810Z 
2023-11-30T22:00:33.6904980Z MainThreadFileSystemEventService#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: file:///usr/local/share/dotnet/packs/, recursive: true, session: 0.1325660403686899): EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/usr/local/share/dotnet/packs/'
2023-11-30T22:00:34.7766350Z FAIL Razor Integration Tests test/razorIntegrationTests/formatting.integration.test.ts (15.65 s)
```

**Comment by gregg-miskelly** [comment]
@davidwengier @dibarbet is there actually a way to skip tests?

**Comment by davidwengier** [comment]
@gregg-miskelly I believe to skip you change `test` to `test.skip` here: https://github.com/dotnet/vscode-csharp/blob/main/test/razorIntegrationTests/formatting.integration.test.ts#L31

But looks like you have green builds now 🤷‍♂️

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need support

**Pull request merged**
