### PR TITLE
Close all text editors after each test.

### PR DESCRIPTION
**Pull request by JoeRobich**
This is a test to see if it improves integration test reliability.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@dibarbet first try!

**Comment by JoeRobich** [comment]
two for two!

**Comment by JoeRobich** [comment]
Third run and only an O# failing test. Seems to be alright.

**Review by arkalyanms — APPROVED** [review]

**Review by dibarbet — COMMENTED** [review]
nice!

**Pull request merged**
